# Generated by Django 3.0.5 on 2020-06-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default=None, upload_to='uploads/%Y-%m-%d/')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=300)),
                ('qualification', models.CharField(max_length=75)),
                ('experience', models.DurationField(default=0)),
                ('date_of_joining', models.DateField(default=datetime.datetime(2020, 6, 10, 21, 44, 8, 507141))),
                ('department', models.DateField(choices=[('General medicine', 'General medicine'), ('General surgery', 'General surgery'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')])),
                ('doctorate_copy', models.FileField(default=None, upload_to='uploads/%Y-%m-%d/')),
                ('shift', models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], max_length=5)),
            ],
        ),
    ]
