# Generated by Django 3.1 on 2020-09-03 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default=None, upload_to='uploads/%Y-%m-%d/')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address', models.TextField(max_length=300)),
                ('qualification', models.CharField(max_length=75)),
                ('experience', models.IntegerField(default=0)),
                ('date_of_joining', models.DateField(default=datetime.datetime.now)),
                ('department', models.CharField(choices=[('', 'Department'), ('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')], max_length=17)),
                ('doctorate_copy', models.FileField(default=None, upload_to='uploads/%Y-%m-%d/')),
                ('shift', models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.TextField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='out_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('consultant_doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.doctors')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.patients')),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('consultant_doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.doctors')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.patients')),
            ],
        ),
    ]
