# Generated by Django 3.0.5 on 2020-06-10 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 22, 4, 35, 103940)),
        ),
        migrations.AlterField(
            model_name='doctors_database',
            name='department',
            field=models.DateField(choices=[('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')]),
        ),
    ]
