# Generated by Django 3.1 on 2020-09-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
    ]
