# Generated by Django 3.0.5 on 2020-06-10 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0004_auto_20200610_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.TextField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 6, 10, 22, 37, 41, 425323))),
            ],
        ),
        migrations.AddField(
            model_name='doctors_database',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 22, 37, 41, 425323)),
        ),
    ]
