# Generated by Django 3.0.5 on 2020-06-10 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0005_auto_20200610_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('patient_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('consultant_doctor', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=10)),
                ('complaint_and_history', models.TextField(max_length=1000)),
                ('Diagnosis', models.TextField(max_length=1000)),
                ('medicines', models.TextField(max_length=1000)),
                ('next_checkup', models.DateField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 22, 51, 31, 280964)),
        ),
        migrations.AlterField(
            model_name='patient_database',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 22, 51, 31, 296592)),
        ),
    ]
