# Generated by Django 3.0.5 on 2020-06-10 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0006_auto_20200610_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 22, 54, 34, 760508)),
        ),
        migrations.AlterField(
            model_name='patient_database',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 22, 54, 34, 760508)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 22, 54, 34, 776137)),
        ),
    ]
