# Generated by Django 3.0.5 on 2020-06-11 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0007_auto_20200610_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 7, 24, 48, 648602)),
        ),
        migrations.AlterField(
            model_name='patient_database',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 7, 24, 48, 648602)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 7, 24, 48, 648602)),
        ),
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.CharField(choices=[('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')], max_length=20),
        ),
    ]
