# Generated by Django 3.0.5 on 2020-06-11 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0009_auto_20200611_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 7, 47, 56, 12015)),
        ),
        migrations.AlterField(
            model_name='patient_database',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 2, 17, 56, 12015, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 2, 17, 56, 12015, tzinfo=utc)),
        ),
    ]
