# Generated by Django 3.0.5 on 2020-06-11 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0010_auto_20200611_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 7, 49, 34, 926455)),
        ),
        migrations.AlterField(
            model_name='patient_database',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
