# Generated by Django 3.0.5 on 2020-06-11 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0011_auto_20200611_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 21, 3, 13, 527403)),
        ),
        migrations.AlterField(
            model_name='doctors_database',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
