# Generated by Django 3.0.5 on 2020-06-11 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0012_auto_20200611_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 21, 7, 17, 880755)),
        ),
    ]
