# Generated by Django 3.0.5 on 2020-06-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0014_auto_20200611_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Diagnosis',
            new_name='diagnosis',
        ),
    ]
