# Generated by Django 3.0.7 on 2020-07-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0016_report_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='out_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('consultant_doctor', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
