# Generated by Django 3.0.7 on 2020-07-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0017_out_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_patient',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
