# Generated by Django 3.0.7 on 2020-07-05 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0018_auto_20200705_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_patient',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
