# Generated by Django 3.0.7 on 2020-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0019_auto_20200705_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_patient',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
