# Generated by Django 3.0.7 on 2020-07-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0020_auto_20200705_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_patient',
            name='department',
            field=models.CharField(choices=[('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')], max_length=30),
        ),
    ]
