# Generated by Django 3.0.7 on 2020-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0021_auto_20200706_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_database',
            name='department',
            field=models.CharField(choices=[('', 'Department'), ('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')], max_length=17),
        ),
        migrations.AlterField(
            model_name='out_patient',
            name='department',
            field=models.CharField(choices=[('', 'Department'), ('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')], max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='Department',
            field=models.CharField(choices=[('', 'Department'), ('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')], max_length=20),
        ),
    ]
