# Generated by Django 3.1b1 on 2020-07-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0022_auto_20200706_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('consultant_doctor', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('', 'Department'), ('General medicine', 'General medicine'), ('Urology', 'Urology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Dental', 'Dental')], max_length=30)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
