# Generated by Django 3.1b1 on 2020-07-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0024_auto_20200715_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_database',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
