# Generated by Django 3.1b1 on 2020-07-15 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_management_system', '0026_auto_20200715_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_database',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
