# Generated by Django 3.1b1 on 2020-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0027_auto_20200715_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_database',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
