# Generated by Django 3.1b1 on 2020-07-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0028_auto_20200715_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out_patient',
            name='consultant_doctor',
        ),
        migrations.RemoveField(
            model_name='out_patient',
            name='created',
        ),
        migrations.RemoveField(
            model_name='out_patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='out_patient',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='out_patient',
            name='name',
        ),
        migrations.AddField(
            model_name='out_patient',
            name='consultant_doctor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.doctors_database'),
        ),
        migrations.AddField(
            model_name='out_patient',
            name='patient_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.patient_database'),
        ),
    ]
