# Generated by Django 3.1b1 on 2020-07-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0029_auto_20200717_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='out_patient',
            old_name='consultant_doctor_id',
            new_name='consultant_doctor',
        ),
        migrations.RenameField(
            model_name='out_patient',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
