# Generated by Django 3.1b1 on 2020-07-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0030_auto_20200717_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_patient',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
