# Generated by Django 3.1b1 on 2020-07-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0031_out_patient_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.patient_database'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultant_doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_management_system.doctors_database'),
        ),
    ]
