# Generated by Django 3.1b1 on 2020-08-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0032_auto_20200728_0718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctors_database',
            new_name='doctors',
        ),
        migrations.RenameModel(
            old_name='patient_database',
            new_name='patients',
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
