# Generated by Django 3.1 on 2020-09-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management_system', '0035_auto_20200902_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
    ]
